name: Receive PR

# read-only repo token
# no access to secrets
on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
#       - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: print User Name
        run: echo ${{ secrets.DOCKER_HUB_USERNAME }}
      - name: print Dir
        run: ls -la
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: docker build & tag
        run: docker build -t woojang1230/github-action-test:1.0 && docker tag woojang1230/github-action-test:1.0 woojang1230/github-action-test:latest
      - name: docker push
        run: docker push woojang1230/github-action-test:1.0 && docker push woojang1230/github-action-test:latest
